# Generated by Django 4.2.23 on 2025-07-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('Suppliers', 'Suppliers'), ('Services', 'Services'), ('Contractors', 'Contractors')], default='Suppliers', max_length=50),
        ),
    ]
